---

- name: Manage databases
  become: true
  become_user: "{{ influxdb_install_user }}"
  script: "manage_influx_database.sh {{ item }}"
  register: manage_influx_database_result
  changed_when: "manage_influx_database_result.rc == 10"
  failed_when: "manage_influx_database_result.rc != 0 and manage_influx_database_result.rc != 10"
  with_items: "{{ influxdb_databases }}"
  tags:
    - influxdb
    - administration

- name: Manage users and rights
  become: true
  become_user: "{{ influxdb_install_user }}"
  command: "manage_influx_user.sh --user-type {{ item.type }} --user-name {{ item.name }} --user-password {{ item.password }} {{ item.rights | default([]) | join(' ') }}"
  register: manage_influx_user_result
  changed_when: "manage_influx_user_result.rc == 10"
  failed_when: "manage_influx_user_result.rc != 0 and manage_influx_user_result.rc != 10"
  with_items: "{{ influxdb_users }}"
  tags:
    - influxdb
    - administration
