---

- name: Ensure the system can use the HTTPS transport for APT
  become: true
  become_user: "{{ influxdb_install_user }}"
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport
  tags:
    - influxdb
    - packages

- name: Install HTTPS transport for APT
  become: true
  become_user: "{{ influxdb_install_user }}"
  apt:
    name: "apt-transport-https"
    state: present
  when: not apt_https_transport.stat.exists
  tags:
    - influxdb
    - packages

- name: Download apt key
  become: true
  become_user: "{{ influxdb_install_user }}"
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present
  tags:
    - influxdb
    - packages

- name: Add apt repository for debian wheezy
  become: true
  become_user: "{{ influxdb_install_user }}"
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian wheezy stable"
    filename: "influxdb"
    state: present
  when: ansible_distribution_major_version == '7'
  tags:
    - influxdb
    - packages

- name: Add apt repository for debian jessie
  become: true
  become_user: "{{ influxdb_install_user }}"
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian jessie stable"
    filename: "influxdb"
    state: present
  when: ansible_distribution_major_version == '8'
  tags:
    - influxdb
    - packages

- name: Install package
  become: true
  become_user: "{{ influxdb_install_user }}"
  apt:
    name: influxdb
    state: present
    update_cache: yes
  notify:
    - restart influxdb
  tags:
    - influxdb
    - packages
