---

- name: Install for debian
  include: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: Write config
  become: true
  become_user: "{{ influxdb_install_user }}"
  template:
    src: influxdb.conf.j2
    dest: "{{ influxdb_config_dir }}/{{ influxdb_config_file }}"
    group: "{{ influxdb_group }}"
    owner: "{{ influxdb_user }}"
    backup: yes
  notify:
    - restart influxdb
  tags:
    - influxdb

- name: start influxdb service
  become: true
  become_user: "{{ influxdb_install_user }}"
  service:
    name: influxdb
    state: started
  tags:
    - influxdb

- name: Manage databases and users
  include: administration.yml
